### ISSUE TITLE
Error while building QT5 application

### ISSUE THREAD

**Issue by tfateba** [pbouda/buildroot-qt-dev#8]
Hello, there is a problem while cloning the repository https://github.com/pbouda/brummbeere.git
All file inside the directory beere-qml-components are missing. So there is a compilation error while running make command.

Cheers, Theo.

**Comment by pbouda** [comment]
You probably have to init the sub-module:
```
$ git submodule init
$ git submodule update
```
It's mentioned in the documentation:
http://brummbeere.readthedocs.io/en/latest/compiling.html

**Comment by tfateba** [comment]
Thank you for your answer.
